### ISSUE TITLE
Survival Island corrupted

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#40] opened 2016-12-18 12:44 UTC
The bottom text "START" changes to something like "SRM RT" as soon as you start entering the code (press 
fire). No clue what is causing that.

[Survival Island (1983) (Starpath).zip](https://github.com/DirtyHairy/stella/files/659416/Survival.Island.1983.Starpath.zip)

**Comment by DirtyHairy** [comment] 2016-12-18 14:13
That one is interesting. I don't have any clue how this could be connected to the new core, but it seems to me that the program state gets corrupted (RAM, either built-in or Supercharger):

 * The very same ROM works fine on 6502.ts
 * The code looks pretty standard, if this fails, then alot of other things should fail as well
 * The text actually really looks like "SRM RT", and as much as I try, I can't imagine any way how this could be the result of a positioning or delay glitch

@sa666666 , @thrust26 do you have any ideas? Otherwise, I think we will have to wait until we have a working debugger again.

**Comment by DirtyHairy** [comment] 2016-12-18 14:33
Things are even weirder: I continued to play with the debugger, and the code I find for drawing the text (after fire has been pressed, haven't checked before) differs between the two cores. Not surprisingly, what I find for the old core matches what I find with the 6502.ts debugger:

Old core:
![debug_old](https://cloud.githubusercontent.com/assets/2444224/21294144/98ea075a-c536-11e6-960e-a0fa5d94868a.png)

New core:
![debug_new](https://cloud.githubusercontent.com/assets/2444224/21294147/a19449e2-c536-11e6-83c4-03dcc50cf5a0.png)

6502.ts:
![debug_6502ts](https://cloud.githubusercontent.com/assets/2444224/21294179/569e1c28-c537-11e6-8925-2b8fb8c201a5.png)

**Comment by thrust26** [comment] 2016-12-18 14:52
This is really crazy. I agree that this is most likely not related to the new core.

@sa666666 Any idea what's happening here?

**Comment by sa666666** [comment] 2016-12-18 15:03
I just compiled a few older versions, and the bug first appeared in https://github.com/DirtyHairy/stella/commit/e786b3307e4ee5470a5aa8d05c957de1e7c4e810, which is when latched input was enabled.  So I guess we should start looking there first.

**Comment by thrust26** [comment] 2016-12-18 15:11
At $FD43... I found the code which modifies the RAM at $FCF8...

**Comment by DirtyHairy** [comment] 2016-12-18 15:12
Interesting. I did the same thing (examine older versions), but it seems I didn't go back far enough. This suggests that there is some bug in INPTx handling that causes the ROM to misbehave. Unfortunately, I have to leave now.

**Comment by thrust26** [comment] 2016-12-18 15:23
The bug results from reading INPT5|$30. With no right joystick attached, bit 7 should be set. But the bit must be clear and therefore the first two kernel graphic pointers are modified.

**Comment by DirtyHairy** [comment] 2016-12-18 21:03
Ouch, just a stupid typo fixed in f4932b8 INPT5 was wired to the left port instead of the right one. Still, the consequences are interesting. For the laughs, it turns out that you can reproduce this by pressing left and right fire simultanously. What were the people at Arcadia thinking... :tada:

**Closed by DirtyHairy** 2016-12-18 21:03 UTC
