### ISSUE TITLE
Regression in G.I. Joe

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#38] opened 2016-12-18 01:28 UTC
I believe the following wasn't an issue in pre2, so it must come from the last few commits.  The house on the bottom-left is affected.  These snapshots are in debug mode, so the issue can be seen more easily.

The first is from the old core, which I confirmed on real hardware is correct (specifically, the overhang of the roof is only one pixel):
![screenshot_20161217_214616](https://cloud.githubusercontent.com/assets/16061066/21290803/32ed978e-c4a3-11e6-948d-608607bed901.png)

This one is from pre1:
![screenshot_20161217_221119](https://cloud.githubusercontent.com/assets/16061066/21290867/d226e8bc-c4a5-11e6-852b-c929bead7c78.png)

This is from the most current commit (pre2 and later).  There is some displacement, the overhang is two pixels, and there is now a hole in the roof:
![screenshot_20161217_214636](https://cloud.githubusercontent.com/assets/16061066/21290804/32edbf8e-c4a3-11e6-96cc-c2f28f7bb0c8.png)

For some strange reason, it seems the priority is incorrect too (although I can't be sure that's not an issue in the old core; the hole in the roof is the biggest problem).

**Comment by thrust26** [comment] 2016-12-18 09:14
A score mode priority fix was introduced in 4.7.

>  * Fixed bug in 'Score mode' in TIA emulation; the TIA object colours were correct, but the associated priority was sometimes incorrect.

More info here:
http://atariage.com/forums/topic/243146-stella-465-released/page-3#entry3404164

**Comment by thrust26** [comment] 2016-12-18 09:30
As for the pixel, the code overwrites HMP0 from $0x with $Fx **during** HMOVE:
`f800 sta HMOVE`
`f802 sta HMP0`

This moves P0 by one pixel from 11 to 12. It seems that your code moves to 13 here (a working debugger would be helpful).

**Comment by DirtyHairy** [comment] 2016-12-18 09:59
Thanks for the pointer, Thomas; I'll look into this later when I find time. Indeed, my last commit introduced a slight change to HMPx during HMOVE.

As for debugging, I currently identify the relevant addresses to break on with Stella (old core) and then use the 6502.ts debugger and the Chrome devtools to dig into the emulation state.

**Comment by DirtyHairy** [comment] 2016-12-18 21:58
Fixed in 7d7c0f6 . The regression was introduced in 839ba71 when I introduced a shift of one pixel for RESx during extended hblank. I have shifted the threshold for this, and this leaves G.I. Joe with an intact roof and also fixes a slight glitch in eshu's `long005.bin` demo. However, I'd like to experiment with this on real hardware at some point to make sure that the threshold is correct.

**Closed by DirtyHairy** 2016-12-18 21:58 UTC
Labels: bug, glitched game, possible regression

**Comment by thrust26** [comment] 2016-12-18 22:01
How much can/do you rely on existing documentation (e.g by Andrew Towers)?

**Comment by DirtyHairy** [comment] 2016-12-18 22:30
I rely on Andrew Towers' notes as much as possible, but there are some exceptions that are not covered by the notes. Particular examples are:

 * Positioning during hblank. There's only one rather vague sentence in the notes
 * RESPx during decode. AT states that the decode is either delayed by 1, 2 or 3 cycles or completely gobbled depending on exact timing, but no details are given.
 * NUSIZ during decode. There's nothing in the notes, but the effect must be there in order for Meltdown to work

There are other examples. Some things you can find by a careful search through the forums, and some are basically trial and error :smirk: I view it like this: you can build a pretty good core from following AT's notes, but you have to experiment and make assumptions on how the logic works in order to go further.

Reading the schematics might help someone more hardware-oriented, but I never was good with electronics, so that'd be a waste of time :smirk:

**Comment by thrust26** [comment] 2016-12-18 22:57
I was asking because I think its a good idea to document the yet undocumented findings.

**Comment by DirtyHairy** [comment] 2016-12-18 23:11
I agree. I have been thinking about writing up an overview of the core and the implemented algorithms after Stella 5.0 has been released that should be detailed enough to recreate the core from scratch (together with ATs notes).

**Comment by thrust26** [comment] 2016-12-19 17:07
BTW: The priority is still wrong.

**Comment by sa666666** [comment] 2016-12-19 17:21
Are you sure the priority is wrong now, or was it wrong in the old core?  The 'score mode priority fix' you mentioned above has already been implemented in the new core, and tested with the test ROMs from  the link you provided.

**Comment by thrust26** [comment] 2016-12-19 17:34
I stand corrected. I just tested old and new core with the test binary above and with the TIM1T demo. The new core works correctly in all cases. The fix in the old core only fixed TIM1T.

http://atariage.com/forums/topic/249107-stella-471-released/#entry3459686
