### ISSUE TITLE
SaveKey updates delayed in launcher

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#20] opened 2016-12-08 10:30 UTC
This bug is **not** related to the new core.

When you start a game from the Stella launcher and save a new high score on the SaveKey, go back to the launcher and start the same game again, the new high score is not loaded but the previous one. You have to go back to the launcher again and restart the game a 2nd time to get the new high score loaded.

This problem does not happen when you start a game directly (via command line) without the launcher.

**Comment by sa666666** [comment] 2016-12-08 21:32
I'll bet it's the file representing the SaveKey memory not being closed, so you're getting what was in the file before it is sync'ed to disk.  Can you suggest a ROM to play to illustrate this?

**Comment by thrust26** [comment] 2016-12-08 21:39
Three.s simply stores the high score. You can reset the high score by pressing down and fire when you start the ROM.
[Three.s (v1.02).zip](https://github.com/DirtyHairy/stella/files/640642/Three.s.v1.02.zip)

**Comment by sa666666** [comment] 2016-12-09 13:52
I must be using this ROM incorrectly, because I can't get it to save anything at all, either from the UI or the commandline.  I check the savekey_eeprom.dat file, and its modification date doesn't change, indicating it's not being written to at all.  The file is being opened correctly, but is never being written out to disk, since nothing changes during playing the ROM.

**Comment by thrust26** [comment] 2016-12-09 14:12
Probably a stupid question: Have you set the properties for right controller to SaveKey?

**Comment by sa666666** [comment] 2016-12-09 14:21
Yes, and I modified the relevant code with print statements to see that the file is indeed being opened.  But in writing the file, there's a check to determine if anything changed in the in-memory buffer.  If nothing changed, then the file isn't written.  So I guess my question is: how exactly do I use this ROM to get it to save something to the SaveKey?

**Comment by thrust26** [comment] 2016-12-09 15:08
You just have to play a game until the end. It doesn't save before.

**Comment by sa666666** [comment] 2016-12-09 15:32
Still no luck.  There are several issues.  First, when not using the SaveKey starts up with the following image:
![normal](https://cloud.githubusercontent.com/assets/16061066/21054109/d9996e4e-be06-11e6-9732-ded5e4034ed4.png)
Then when using the SaveKey, the image looks as follows:
![savekey](https://cloud.githubusercontent.com/assets/16061066/21054123/e46c31e4-be06-11e6-8b1d-4d35b95b1101.png)

I'm working with the latest released version of Stella 4.7.3 (just to be sure it has nothing to do with the new core).  I enabled full debug output in the MT24LC256 class, and while it shows output when starting the ROM (I assume to load the old info), it doesn't show any output at all when exiting the ROM.  So this is why nothing is being written, and why you don't see the new score next time.

Did you use the most recent I2C files when compiling this?  Recall that there were I2C files floating around that didn't match the specs of real hardware, which is what Stella is emulating.

**Comment by thrust26** [comment] 2016-12-09 16:30
That's **very** weird. 

I am using Stella 4.7.3 too. And for me it saves the high scores and doesn't display like in your 2nd screenshot. Also when I start the ROM again from the launcher, it loads the new high score. 

Something seems very wrong...

**Comment by sa666666** [comment] 2016-12-09 16:40
I will try this in Windows when I get home (since that's what you're using, correct?).  I have absolutely no idea why the display is garbled simply from enabling the SaveKey.

**Comment by DirtyHairy** [comment] 2016-12-09 16:43
Just a suggestion: @sa666666, you could try running Stella on this ROM through valgrind, maybe there is memory corruption somewhere --- that would explain the Heisenbug.

**Comment by thrust26** [comment] 2016-12-09 16:47
Windows 10, yes.

**Comment by sa666666** [comment] 2016-12-09 17:01
Just to confirm before I research any further: the md5sum for this ROM is b7d0aae399781b3c18679debda6d32b1 ??

**Comment by thrust26** [comment] 2016-12-09 17:06
Yup.

**Comment by thrust26** [comment] 2016-12-09 17:16
To me it looks like corrupt values are read from SaveKey. Those cause the digit pointers to cross a page and then that makes the WSYNC-less kernel go mad.

**Comment by sa666666** [comment] 2016-12-09 17:32
OK, it was the flash not being initialized correctly.  I see the error, and it was as I suspected; the ROM isn't closing the file before re-opening it, so you're seeing the old version.  That's why it takes 2 loads of the ROM to see the score.  I will fix this soon.

**Comment by thrust26** [comment] 2016-12-09 17:45
Is that a bug in my code?

**Comment by sa666666** [comment] 2016-12-09 18:04
No, the problem is in Stella, and how it doesn't destruct one ROM object before opening another one (so when you open the new ROM instance, it sees the original savekey data).  Later, when the ROM is closed and opened again, the new data has been saved, and you see the new score.

Launching from the commandline doesn't work the same way, so that's why the bug doesn't happen there.

**Comment by sa666666** [comment] 2016-12-09 22:36
Fixed in https://github.com/DirtyHairy/stella/commit/f7e712386bf3392f289c27da10163e075ed26481.

**Closed by sa666666** 2016-12-09 22:36 UTC

**Comment by thrust26** [comment] 2016-12-10 09:47
> Launching from the commandline doesn't work the same way, so that's why the bug doesn't happen there.

That explains why I didn't find that bug much earlier. :)
